# Generated by Django 5.0.3 on 2024-03-11 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attempts', models.IntegerField()),
                ('distribution_type', models.CharField(choices=[('random', 'Random'), ('uniform', 'Uniform')], max_length=20)),
                ('current_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_attempts', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
            ],
            options={
                'db_table': 'boxes',
            },
        ),
        migrations.CreateModel(
            name='UserBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.box')),
            ],
            options={
                'db_table': 'user_boxes',
            },
        ),
    ]
